HewlettPackard/squest

docs/dev/dev-env.md
mkdocs.yml

- ask to run npm install before to need node-modules
- typing mistakes correction in mkdocs.yml

documentation update

---

service_catalog/urls.py
service_catalog/views/common.py
templates/navbar.html
templates/registration/profile.html

shows username, first name, last name, email, last login and creation date of the current user.

Add profile page to show user information

---

service_catalog/forms/customer_forms.py
service_catalog/forms/utils.py
tests/base.py
tests/test_forms/test_admin_forms.py
tests/test_forms/test_forms_utils.py
tests/test_models/test_operations.py

Multiselect, text area, password, integer and float fields have been added. The initial values and validators were mapped with values defined in survey spec.

Several additional fields types are available in surveys.

---

docker/squest.Dockerfile
full-env.docker-compose.yml

[Fix] fix docker image. Now prepare a writable media folder

---

service_catalog/forms/admin_forms.py
service_catalog/models/job_templates.py
templates/service_catalog/admin/instance/instance-list.html
templates/service_catalog/admin/request/request-list.html
templates/service_catalog/settings/catalog/service/operation/operation-list.html
tests/test_views/admin/settings/catalog/services/test_create.py

- update _str_ method of job template model to show the linked Tower instance
- add links on instance or request object in views

[Fix] fix #56 when using same job template name on different AWX

---

docker/squest.Dockerfile
docs/dev/dev-env.md
poetry.lock
pyproject.toml
resource_tracker/models.py
resource_tracker/urls.py
resource_tracker/views/__init__.py
resource_tracker/views/resource_tracker_graph.py
templates/resource_tracking/graph/resource-tracker-graph.html
templates/resource_tracking/graph/resource_group.j2
templates/resource_tracking/graph/resource_pool.j2
templates/sidebar.html

Resource Tracking view 

---

service_catalog/forms/utils.py

Map question_description from AWX on help_text

---

service_catalog/forms/admin_forms.py
service_catalog/forms/customer_forms.py
templates/service_catalog/customer/catalog/service/service-request.html
tests/test_forms/test_admin_service_forms.py
tests/test_forms/test_customer_request_forms_on_restricted_service.py
tests/test_forms/test_service_request_form.py

Issue fixed :
#88 #43
Must add documentation of billing group

add billing field for create request form + fix on edit service form

---

docs/index.md
docs/manual/billing_groups.md
mkdocs.yml

Billing group doc

---

.github/workflows/on-merge-master.yml
.github/workflows/on-pull-request-workflow.yml
README.md
Squest/settings/__init__.py
docs/contribute/documentation.md
mkdocs.yml
poetry.lock
pyproject.toml
templates/base.html
templates/navbar.html

update CI/CD to build mkdocs

---

service_catalog/filters/support_filter.py
service_catalog/templatetags/admin_data.py
service_catalog/urls.py
service_catalog/views/__init__.py
service_catalog/views/admin/support.py
templates/service_catalog/admin/dashboard.html
templates/service_catalog/admin/instance/instance-details.html
templates/service_catalog/admin/support/support-list.html
templates/sidebar.html
tests/test_views/admin/support/test_support_view.py

add support page

---

profiles/urls.py
profiles/views/__init__.py
profiles/views/user_views.py
resource_tracker/filtersets.py
templates/profiles/group/user-by-group-list.html
templates/profiles/user-list.html
templates/resource_tracking/resource_pool/resource-pool-list.html
templates/service_catalog/admin/dashboard.html
templates/sidebar.html

List users in page with filter by billing groups.
Issue #85

User list page

---

service_catalog/views/common.py
tests/test_dashboards/test_pie_charts.py

Second fix for #114 
Yesterday when I tried to reproduce the bug mentioned here: #114 we just reproduce #76 
This fix is the good one for #114

fix for #114-part2

---

service_catalog/forms/admin_forms.py
templates/generics/form_edit.html
templates/service_catalog/admin/service/service-create.html
templates/service_catalog/admin/service/service-edit.html
tests/test_views/admin/settings/catalog/services/test_create.py

[Fix] fix media upload with generic form edit

---

service_catalog/models/__init__.py
service_catalog/models/request.py
service_catalog/models/request_state.py
templates/custom_columns/request_actions.html
templates/service_catalog/admin/request/request-accept.html
tests/test_views/admin/request/test_admin_request_view.py

Accept button renamed + allow to review after first accept

---

service_catalog/models/request.py
service_catalog/tables/request_tables.py
service_catalog/urls.py
service_catalog/views/admin/request.py
templates/service_catalog/admin/request/request-details.html
templates/service_catalog/common/instance-details.html
tests/test_views/admin/request/test_admin_request_view.py

add admin request details page

---

service_catalog/forms/admin_forms.py
service_catalog/forms/customer_forms.py
service_catalog/forms/utils.py
templates/generics/form_edit.html
templates/service_catalog/admin/request/request-accept.html
templates/service_catalog/common/service/service-request.html
templates/sidebar.html
tests/test_forms/test_forms_utils.py

titles to identify survey fields and squest fields in request form added + empty value for choices fields added

---

service_catalog/api/admin/instance_api_views.py
service_catalog/serializers/instance_serializer.py
tests/test_service_catalog/test_api/test_admin/test_instance/test_create.py

add create operation on instance model from API

---

resource_tracker/forms/resource_group_attribute_definition_form.py
resource_tracker/models/resource_group_attribute_definition.py
resource_tracker/views/resource_group_attribute_views.py
tests/test_resource_tracker/test_models.py
tests/test_resource_tracker/test_resource_group_attribute_views.py

- fix clean method in ResourceGroupAttributeDefinitionForm
- fix resource pool was not updated after adding or removing producer/consumer from an attribute

couple fixes

---

profiles/migrations/_rbac.py
resource_tracker/api/resource_group_api_views.py
resource_tracker/api/resource_pool_api_views.py
tests/test_resource_tracker/test_api/test_resource_group_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_pool_api_views/test_list.py

[Feature] API - get resource group/pool by name

---

service_catalog/api/operation_api_views.py
service_catalog/api/request_api_views.py
service_catalog/api/urls.py
service_catalog/serializers/dynamic_survey_serializer.py
service_catalog/serializers/request_serializers.py
tests/test_service_catalog/test_api/test_request/test_service_request_create.py

+ remove get api endpoint for /service/<id>/request

[Fix] fix swagger generated doc with service request

---

resource_tracker/tables/resource_tables.py
tests/test_resource_tracker/test_resource_group_resource_views.py

[Fix] fix generic list of resource after deleting an attribute

---

docker/squest.Dockerfile

[Fix] add missing static folder creation in Dockerfile

---

templates/generics/list.html

[Fix] fix key error exception when no data in table

---

docs/manual/metrics.md
monitoring/models.py

Quota metrics

---

Squest/settings.py
docker-compose.yml
docker/environment_variables/redis.env
docker/environment_variables/squest.env
poetry.lock
pyproject.toml
templates/base.html
templates/sidebar.html

Before cache requests per second: 9
After cache requests per second: 84
Testing script:
```bash
SQUEST_HOST=127.0.0.1
SQUEST_PORT=8000
LOGIN_URL="http://${SQUEST_HOST}:${SQUEST_PORT}/accounts/login/"
INSTANCE_LIST_URL="http://${SQUEST_HOST}:${SQUEST_PORT}/ui/service_catalog/instance/"
YOUR_USER='admin'
YOUR_PASS='admin'
COOKIES=/home/nico/Documents/squest/cookies.txt
CURL_BIN="curl -c $COOKIES -b $COOKIES -e $LOGIN_URL"
echo -n "Get middleware token ..."
$CURL_BIN $LOGIN_URL > /dev/null
DJANGO_MIDDLEWARE_TOKEN="csrfmiddlewaretoken=$(grep csrftoken $COOKIES | sed 's/^.*csrftoken\s*//')"
echo "${DJANGO_MIDDLEWARE_TOKEN}"
echo -n "Perform login ..."
$CURL_BIN \
-d "${DJANGO_MIDDLEWARE_TOKEN}&username=${YOUR_USER}&password=${YOUR_PASS}" \
-X POST $LOGIN_URL
DJANGO_TOKEN="$(grep csrftoken …
```

[Internal] add redis cache

---

resource_tracker/api/serializers/resource_group/resource_serializers.py
service_catalog/models/request.py
tests/test_resource_tracker/test_api/test_resource_api_views/test_patch.py
tests/test_resource_tracker/test_api/test_resource_api_views/test_update.py
tests/test_service_catalog/test_models/test_request.py

[Enhancement] Catch all exceptions in processing request

---

resource_tracker/views/resource_tracker_graph.py
service_catalog/models/operations.py

Prefix name with RG and RP

---

service_catalog/api/views/instance_api_views.py
tests/test_service_catalog/test_api/test_instance/test_instance_delete.py

[Enhancement] Instance can be deleted by an admin from API

---

service_catalog/tables/instance_tables.py
service_catalog/urls.py
service_catalog/views/instance.py
service_catalog/views/instance_list_view.py
tests/test_service_catalog/test_views/test_admin/test_instance/test_instance_bulk_delete.py

[Feature] Bulk delete for Instances

---

templates/service_catalog/admin/request/request-accept.html

[Enhancement] show specs on accept/review page

---

Squest/settings.py
tests/test_profile/test_api/test_billing_group/test_billing_group_list.py
tests/test_profile/test_api/test_quota/test_quota_list.py
tests/test_profile/test_api/test_quota_binding/test_quota_binding_list.py
tests/test_profile/test_api/test_user/test_user_list.py
tests/test_resource_tracker/test_api/test_resource_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_group_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_group_api_views/test_rg_attribute_definition_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_group_api_views/test_rg_text_attribute_definition_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_pool_api_views/test_list.py
tests/test_resource_tracker/test_api/test_resource_pool_api_views/test_rp_attribute_definition_api_views/test_list.py
tests/test_service_catalog/test_api/test_approval_step/test_approval_step_list.py
tests/test_service_catalog/test_api/test_approval_workflow/test_approval_workflow_list.py
tests/test_service_catalog/test_api/test_instance/test_instance_list.py
tests/test_service_catalog/test_api/test_operation/test_operation_list.py
tests/test_service_catalog/test_api/test_operation/test_operation_list_in_instance.py
tests/test_service_catalog/test_api/test_request/test_request_list.py
tests/test_service_catalog/test_api/test_service/test_service_list.py
tests/test_service_catalog/test_api/test_tower_server/test_job_template/test_job_template_list.py
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_list.py

[Enhancement] Add API Pagination

---

service_catalog/api/serializers/dynamic_survey_serializer.py
service_catalog/forms/utils.py
tests/test_service_catalog/test_forms/test_forms_utils.py
tests/test_service_catalog/test_views/test_customer/test_instance/test_instance.py

[Fix] Support choices as list in AWX

---

service_catalog/api/serializers/operation_serializers.py
service_catalog/api/serializers/service_serializers.py
service_catalog/api/serializers/tower_server_serializer.py
service_catalog/api/views/operation_api_views.py
service_catalog/api/views/service_api_views.py
tests/test_service_catalog/test_api/test_operation/test_operation_create.py
tests/test_service_catalog/test_api/test_operation/test_operation_put.py
tests/test_service_catalog/test_api/test_service/test_service_create.py
tests/test_service_catalog/test_api/test_service/test_service_put.py
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_create.py
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_put.py
tests/utils.py

[Fix] The extra_vars field is not valid if it is in JSON from the API.

---

CHANGELOG.md
Squest/version.py
pyproject.toml
service_catalog/views/customer/catalog_views.py
service_catalog/views/instance.py
templates/custom_columns/doc_operations.html

Release 1.7.5

---

service_catalog/filters/instance_filter.py
templates/generics/list.html

+ add label name to spec filters

[Enhancement] update filter sidebar size

---

Squest/views.py
service_catalog/api/serializers/request_serializers.py
service_catalog/models/custom_link.py
service_catalog/tables/custom_link_table.py
templates/home/admin.html
tests/test_service_catalog/test_api/test_request/test_operation_request_create.py

Was saved as string instead of dict.
Fix #542

[Fix] fix day 2 operation fill in survey serializer

---

.github/workflows/build-and-publish-docker-image.yml
.github/workflows/on-merge-master.yml
.github/workflows/on-pull-request-workflow.yml
docs/manual/filters.md
package-lock.json
package.json
project-static/squest/css/squest.css
project-static/squest/js/squest.js
resource_tracker/models/resource_pool_attribute_definition.py
resource_tracker/views/resource_pool_views.py
service_catalog/models/request.py
templates/base.html
templates/resource_tracking/resource_pool/resource-pool-list.html
tests/test_resource_tracker/test_resource_pool_view.py
tests/test_service_catalog/test_models/test_request.py

Refacto resource pool page

---

service_catalog/filters/request_filter.py

add billing group filter on request list page

---

docker-compose.yml

1. Always mount plugins/fields_validators. We just have to put our scripts at the right location.
2. Variables in docker-compose.yml can be overridden easily with an `export SQUEST_IMAGE=mysquest` or with a .env file
Documentation docker: https://docs.docker.com/compose/environment-variables/set-environment-variables/

Docker compose updates

---

CHANGELOG.md
Squest/version.py
docker-compose.yml
docker/scripts/mariadb-init.sh
pyproject.toml

Use mariadb binary instead of mysql
Freeze version in docker-compose

Fix docker deployment from master

---

docs/manual/service_catalog/operation.md
service_catalog/api/serializers/accept_request_serializer.py
service_catalog/api/serializers/approve_workflow_step_serializer.py
service_catalog/api/serializers/dynamic_survey_serializer.py
service_catalog/api/serializers/request_serializers.py
service_catalog/forms/accept_request_forms.py
service_catalog/forms/approve_workflow_step_form.py
service_catalog/forms/form_generator.py
service_catalog/forms/operation_request_forms.py
service_catalog/forms/service_request_forms.py
tests/test_service_catalog/test_forms/test_form_generator.py

add user to the default field surveyr context

---

profiles/templatetags/squest_utils.py

Swap icons

---

docker/nginx.conf

Maintenance is back

---

profiles/templatetags/squest_utils.py

[Fix] Permission allow to show only the linked item in the sidebar group

---

profiles/forms/quota_forms.py
tests/test_profiles/test_forms/test_quota_form.py

[Fix] Remove the quota when limit is unset in form

---

.github/workflows/on-merge-master.yml

https://github.com/jimporter/mike/issues/188

Fix mike deployment

---

CHANGELOG.md
Squest/views.py
project-static/squest/css/squest-dark.css
templates/generics/doc_aside.html
templates/home/home.html
templates/service_catalog/operation_detail.html
templates/service_catalog/service_detail.html

Fix CSS issue + related docs in operation and service + PROCESSING requests in main dashboard

---

CHANGELOG.md
Squest/version.py
pyproject.toml
service_catalog/views/instance.py
tests/test_service_catalog/test_views/test_customer/test_instance/test_instance_details.py

Release 2.7.1

---

k8s/backup.yml
k8s/deploy.yml
k8s/update.yml

Sorry, forgot some module_defaults in my previous PR...

set module_default also for kubernetes.core.helm and kubernetes.core.k8s_info

---

k8s/squest_k8s/tasks/03-rabbitmq.yml

Fix #820 
This worked reliably in my testing, the error did no longer appear.

Fix errors with rabbitmq user and secret creation

---

service_catalog/api/serializers/tower_server_serializer.py
service_catalog/forms/tower_server_forms.py
service_catalog/forms/tower_server_update_token_forms.py
service_catalog/urls.py
service_catalog/views/tower_server.py
templates/service_catalog/buttons/tower_server_new_token.html
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_create.py
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_patch.py
tests/test_service_catalog/test_api/test_tower_server/test_tower_server_put.py
tests/test_service_catalog/test_views/test_admin/test_tools/test_tower/test_update.py

hide token in tower server update

---

Squest/ldap_config.py
docs/configuration/squest_settings.md
docs/manual/advanced/ldap.md

Add environment variable AUTH_LDAP_USER_SEARCH_FILTER
